{% set name = "aioconsole" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0535ce743ba468fb21a1ba43c9563032c779534d4ecd923a46dbd350ad91d234

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - apython = aioconsole:run_apython

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8

test:
  imports:
    - aioconsole
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/vxgmichel/aioconsole
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Asynchronous console and interfaces for asyncio
  description: |
    Asynchronous console and interfaces for asyncio
  doc_url: https://aioconsole.readthedocs.io/
  dev_url: https://github.com/vxgmichel/aioconsole

extra:
  recipe-maintainers:
    - vxgmichel
    - timkpaine
